name: hadoop-cluster

services:
    namenode:
        image: hadoop:namenode
        container_name: namenode
        platform: linux/amd64
        tty: true
        stdin_open: true
        hostname: namenode
        ports:
            - "9870:9870" # NN Web UI
        volumes:
            - ./share:/root/share
        restart: unless-stopped
        networks: [hadoop]

    datanode1:
        image: hadoop:datanode
        container_name: datanode1
        platform: linux/amd64
        tty: true
        stdin_open: true
        hostname: datanode1
        depends_on: [namenode]
        ports:
            - "9864:9864" # DN Web UI
            - "8042:8042" # NM Web UI
        restart: unless-stopped
        networks: [hadoop]

    datanode2:
        image: hadoop:datanode
        container_name: datanode2
        platform: linux/amd64
        tty: true
        stdin_open: true
        hostname: datanode2
        depends_on: [namenode]
        ports:
            - "9865:9864" # DN Web UI
            - "8043:8042" # NM Web UI
        restart: unless-stopped
        networks: [hadoop]

    resourcemanager:
        image: hadoop:resourcemanager
        container_name: resourcemanager
        platform: linux/amd64
        tty: true
        stdin_open: true
        hostname: resourcemanager
        depends_on: [namenode]
        ports:
            - "8088:8088" # RM Web UI
        restart: unless-stopped
        networks: [hadoop]

    historyserver:
        image: hadoop:jobhistoryserver
        container_name: jobhistoryserver
        platform: linux/amd64
        tty: true
        stdin_open: true
        hostname: jobhistoryserver
        depends_on: [resourcemanager, namenode]
        ports:
            - "19888:19888" # JHS Web UI
        restart: unless-stopped
        networks: [hadoop]

networks:
    hadoop:
        driver: bridge
