FROM hadoop:base

USER root

# Startup script
COPY docker/scripts/start-resourcemanager.sh /usr/local/bin/start-resourcemanager.sh
RUN chmod +x /usr/local/bin/start-resourcemanager.sh

# ResourceManager Web UI
EXPOSE 8088

ENTRYPOINT ["/usr/local/bin/start-resourcemanager.sh"]
