FROM hadoop:base

USER root

# Startup script
COPY docker/scripts/start-namenode.sh /usr/local/bin/start-namenode.sh
RUN chmod +x /usr/local/bin/start-namenode.sh

# NameNode RPC and Web UI
EXPOSE 9870

# Persist name dir
VOLUME ["/root/hadoop/dfs/name"]

WORKDIR /course487/labs

ENTRYPOINT ["/usr/local/bin/start-namenode.sh"]
