FROM hadoop:base

USER root

# Startup script
COPY docker/scripts/start-jobhistoryserver.sh /usr/local/bin/start-jobhistoryserver.sh
RUN chmod +x /usr/local/bin/start-jobhistoryserver.sh

# JobHistoryServer Web UI
EXPOSE 19888

ENTRYPOINT ["/usr/local/bin/start-jobhistoryserver.sh"]
